const rules = [
  {
    name: 'To nie jest blog o mnie, to jest blog od Was, o Was i dla Was. ',
    description:
      'Od czasu do czasu pozwolę sobie nawiązać do osobistych przemyśleń, jednak przede wszystkim będę czerpał z Waszych mądrości (także tych mądrych inaczej). Nie tylko od Czytelników bloga (oby było Was jak najwięcej i zapraszam do aktywności!), ale przede wszystkim od ludzi, których spotkałem już na mojej drodze i których będę spotykał nadal. Już teraz noszę w sobie setki ludzkich historii, opinii i doświadczeń. Mam za sobą tysiące godzin szczerych rozmów o ważnych, życiowych sprawach i decyzjach - tym właśnie mam zamiar się podzielić. Nie wszystkie historie są dobre i pozytywne. Są za to prawdziwe, codzienne i namacalne, a każda jest inna. Mam do nich wielki szacunek, dlatego że są przeżyte i autentyczne. Po prostu ludzkie, człowiecze. Dlatego nie będę pisał o amerykańskiej dreamstory, tylko normalnej rzeczywistości dostępnej każdemu z nas. Ponieważ mam zaszczyt i przyjemność pracować głównie z przedsiębiorcami i innymi ludźmi czynu, spotkałem już na swojej drodze wielu wspaniałych ludzi, którzy na różnych polach odnieśli sukcesy. Dlatego z drugiej strony wiem także, że można pozytywnie. I to jak!! Od nich też czerpię - znajdziecie tu wiele pozytywnych przykładów i postaw. Mam nadzieję, że siła Wielopokoleniowych będzie płynąć właśnie z tego, aby pokazać dobre przykłady, dać szansę zbudować dobre praktyki w każdej rodzinie. Nie chcę jednak przyjmować perspektywy jednego człowieka. Wielopokoleniowa rzeczywistość jest zbyt bogata, aby tak uczynić :) I chociaż - nieskromnie - mam przekonanie, że coś nie coś już o sukcesji i wielopokoleniowych tematach mam do powiedzenia, nie chodzi mi o to, abyś stał się fanem Martyńca. Chcę, abyś został fanem samego siebie i Twojej rodziny - właśnie jako WIELOPOKOLENIOWEJ. Abyś poszerzył perspektywę i podejmował lepsze decyzje, które podniosą jakość Twoich relacji i całego życia.',
  },
  {
    name: 'Nie posiadam monopolu na wiedzę, a tym bardziej na mądrość.',
    description:
      'Nie mam gotowych recept, ani śmiałości mówić komukolwiek, co jest dobre, a co złe. Szanuję wybór każdego z nas - jednostki i grupy ludzi. Nie może być przecież inaczej. Jedyne, co mogę zrobić, to dostarczyć merytorycznej wiedzy, argumentów i przykładów, które uczynią te wybory lepszymi. Coś wnieść do przemyśleń, zmienić perspektywę spojrzenia na dany problem, pomóc nabrać dystansu. Tylko tyle mogę zrobić. Na blogu uchylę rąbka tajemnicy na temat moich własnych przemyśleń, które opiszę szerzej w książkach. Tak, tak, książki też będą. Ale jeszcze nie jestem na nie gotowy. Najpierw trochę poblogujemy ;) Jedyne, co mogę przyjąć za pewnik to to, że im więcej czytasz, słuchasz, obserwujesz, samodzielnie myślisz i starasz się zrozumieć - tym lepsze będzie Twoje życie i Twoje wybory. Mam nadzieję, że poprzez Wielopokoleniowych choć trochę przyczynię się do tego, że będzie co czytać ;)',
  },
  {
    name: 'Obiecuję, że znajdziesz tutaj jedynie moje subiektywne opinie.',
    description:
      'Wiedz, że będą szczere. Ponoszę świadome ryzyko, że ktoś usłyszy niewygodną prawdę, obrazi się, albo też ja sam nie zarobię łatwej kasy, np. na sprzedaży, którą chowałbym pod szyldem blogowania czy doradztwa - wynika to z mojej postawy i podejścia do wielu rzeczy, takich jak wartości, relacje, prawo, finanse osobiste, doradztwo, sprzedaż czy działanie różnego rodzaju korporacji. Będzie to widać w moich wypowiedziach. Wiedz jednak, że są to tylko moje opinie, czyli coś niekoniecznie ważniejszego, niż Twoje własne. A nie jedynie słuszna mądrość i wykładnia rzeczywistości. Nie cierpię takiego podejścia do ego, w którym ktokolwiek przypisuje sobie tego typu racje. Z tego samego powodu nie przepadam za autorytetami, szczególnie tymi „z urzędu”. Sądzę, że nad każdą prawdą można się pochylić i próbować poddać ją w wątpliwość. Oby konstruktywnie i w dobrej wierze, o co skądinąd dzisiaj coraz trudniej. Raz jeszcze powtarzam - to będą tylko moje subiektywne, mniej lub bardziej przemyślane opinie. Sam wciąż się uczę i nie mam zamiaru przestać. Wiedz także, że nie będą kierowane do nikogo personalnie, a już na pewno nie wypowiedziach o charakterze ogólnym. Dlatego proszę nie brać ich do siebie. Jak będę do kogoś coś miał imiennie, to napiszę to wprost. Nie jest moją intencją krytyka osób, lecz ich sposobów myślenia, postaw czy przyzwyczajeń. Tego będę się trzymał i wymagał od moich gości i współpracowników.',
  },
  {
    name: 'Obiecuję, że znajdziesz tutaj jedynie moje subiektywne opinie.',
    description:
      'Choć znajdziesz na Wielopokoleniowych mniej lub bardziej szczegółowe opisy wielu zagadnień prawnych czy finansowych, zastrzegam, że to nie jest doradztwo: prawne, podatkowe, finansowe, czy jakiekolwiek inne. I nie możesz w ten sposób tych wypowiedzi traktować. Z kilku powodów. Po pierwsze doradztwo wymaga bezpośredniej relacji pomięcy doradcą a doradzanym (choćby przez telefon czy e-mail) - konieczny jest szczery dialog i zadawanie pytań. Często jeden szczegół zmienia cały obraz sytuacji. Po drugie prawo jest, jakie jest. Ten sam przepis może być różnie rozumiany przez wielu prawników i to nie tylko w zależności od kontekstu. Ponieważ zaś prawo jest ślepe, może być różnie użyte. Tak jak nóż. Możesz pokroić nim chleb, albo wbić komuś w plecy. Prawo może pomóc we wzajemnych relacjach, uporządkować je i okazać się użyteczne, albo stać się podstawą do wieloletniego nękania z zawiści lub zemsty, albo nadużyć. Tak, o psychologii i mediacji też będzie ;) Po trzecie wreszcie: doradca bierze odpowiedzialność za to co robi i jakie będą skutki jego doradztwa. Przynajmniej powinien to robić, biorąc pod uwagę swoją najlepszą wiedzę, staranność, doświadczenie oraz intencje. Abstrahując w tym miejscu od rozróżnienia doradcy od sprzedawcy, o czym przy okazji opisu postulatów dotyczących doradztwa sukcesyjnego będę pisał sporo. Tymczasem blog jest tylko blogiem (patrz na Zasadę 2 i 3). Nie gniewaj się, że tak to ujmę, a dotyczy to nie tylko tego bloga: odpowiadam za to, co powiedziałem lub napisałem, a nie za to, w jaki sposób to zrozumiałeś, zapamiętałeś bądź wykorzystałeś. Nie biorę i nie mogę wziąć z to odpowiedzialności. Kropka. Moim celem jest popularyzować, a nie uczynić Ciebie prawnikiem; albo zabrać chleb prawnikom, czy też innym doradcom. Wprost przeciwnie - liczę, że częściej będziesz korzystał z usług doradców, lepiej zweryfikujesz ich podejście oraz zadasz bardziej adekwatne pytania. Zaś sami doradcy w większym stopniu zaczną się starać ;) Liczę, że oni także od czasu do czasu tutaj zajrzą. Zapraszam prawników, radców prawnych, adwokatów, notariuszy, sędziów, mediatorów, psychologów, coachów, księgowych, doradców podatkowych, wszelkiego rodzaju pośredników i doradców finansowych, ubezpieczeniowych czy bankowców, a także przedstawicieli świata nauki i blogerów ;) Czytajcie, rozważajcie, komentujcie - każdy głos mile widziany ;)',
  },
  {
    name: 'Solennie przyrzekam blogową transparentność finansową.',
    description:
      'Sądzę, że tak będzie uczciwie. Prowadzę Wielopokoleniowych za własne pieniądze, kosztem innych obowiązków, rodziny i kancelarii sukcesyjnej. Będę to robił niezależnie od tego, czy pojawią się z tego większe przychody - czy nie. Dla jasności, nie mam zamiaru jednak pisać tu o moich prywatnych finansach albo finansach kancelarii, ponieważ nie to jest celem tego bloga. Owszem, będzie o nich tylko raz, obiecałem to już Marcinowi Iwuciowi, ale podcast pojawi się dopiero w lipcu 2022 roku - ujawnię wtedy, dlaczego. Szanuję i podziwiam Michała Szafrańskiego, za to, jak pisze o własnych finansach i jak wiele pokazuje. Jest to wpisane w filozofię bloga jakoszczedzacpieniadze.pl i doskonale tam się sprawdza. U mnie nie, przyjmuję inny cel oraz założenia. Natomiast właśnie m.in. od Michała nauczyłem się ważnej zasady, co niniejszym zobowiązuję się przestrzegać: za każdym razem, kiedy będę miał zamiar zarobić na Tobie, jako na odbiorcy zamieszczanych na Wieolopokoleniowych treści - dowiesz się o tym pierwszy. Zarówno, jeśli sam będziesz miał za to zapłacić, jaki i wtedy, kiedy zapłaci mi ktoś inny. Przyjmuję prostą zasadę: jeśli w danym wpisie czy innym materiale nie ma mowy o pieniądzach czy sponsorach - jest on udostępniany za darmo, staraniem wyłącznie moim, moich współpracowników, a także gości, o ile tacy się pojawią. Jeśli zaś danemu wpisowi  towarzyszyć będzie choćby złotówka przychodu - napiszę o tym wprost. Z czasem pojawią się na Wielopokoleniowych także własne produkty, np. szkolenia czy książki itp. Też będziesz o tym wiedział - zawsze zostawię Ci wybór, czy zechcesz dać mi zarobić, czy nie. Nie ukrywam jednocześnie, że blogowanie nie traktuję jako działalności wyłącznie charytatywnej. Cały czas dostępny jestem jako Kancelaria Sukcesyjna MARTYNIEC w roli doradcy sukcesyjnego lub szkoleniowca do wynajęcia. Na blogu - siłą rzeczy - nie sposób świadczyć usług doradczych. Jednak całość Wielopokoleniowych dostępna będzie zawsze zupełnie za darmo. Traktuję to jako element misji edukacyjnej mojej kancelarii, tak jak od lat zupełnie za darmo piszę, szkolę i popularyzuję temat sukcesji przy różnych okazjach. ',
  },
  {
    name:
      'Podczas blogowania przyjąłem dość swobodną i luźną formę wypowiedzi. ',
    description:
      'Mam nadzieję, że się na to za mnie nie pogniewasz ;) Zrobiłem to z dwóch powodów. Po pierwsze będę poruszał tutaj tematy życiowo trudne, a prosty język ma ułatwić komunikację i rozważania o nich. Postaram się nie nadużywać fachowego słownictwa, choć nie sposób będzie pisać np. o zapisie windykacyjnym, nie posługując się tym wyrażaniem (aby ułatwić Ci życie ułożyłem mój Subiektywny Słowniczek Sukcesyjny). Pomogę także, jak tylko mogę, w zrozumieniu tekstów. Dla ułatwienia przy każdym wpisie znajdziesz jedną, dwie, albo trzy buźki :) Po drugie, cóż, jestem prawnikiem. A prawnicy znani są z tego, że mówią niezrozumiałym językiem i zdarza się, że nawet komunikacja pomiędzy prawnikiem, a jego klientem, jest na tyle nieefektywna, że skutkuje podjęciem błędnych decyzji. Tego chciałbym tutaj uniknąć. Chciałbym, aby w tym miejscu prawo stało się trochę bardziej przyjazne dla nie-prawników, niż jest zazwyczaj. Prawników, księgowych, doradców finansowych i przedstawicieli innych profesji proszę z kolei o wyrozumiałość. Będę tutaj upraszczał, czasem bardzo. Wiem, że tekst postrzegany jako nie-fachowca jako trudny, przez profesjonalistę będzie odbierany jako niedopuszczalny brak precyzji. Ponieważ jednak nie jest to doradztwo - mam nadzieję, że nie wynikną z tego żadne problemy. Po prostu przyjąłem pewną formułę good enough, trochę w oparciu o intuicję. Pamiętaj, że zawsze warto dopytać, sparafrazować i upewnić się, czy dobrze rozumiesz dane zagadnienie lub informację. Masz prawo nie wiedzieć. To żaden wstyd. Nie ma głupich pytań.',
  },
  {
    name: 'Bardzo ważną wartością jest dla mnie wzajemny szacunek. ',
    description:
      'Dlatego proszę Cię o kulturę wypowiedzi oraz szacunek do pozostałych Czytelników. Przede wszystkim w komentarzach czy przy innych okazjach, kiedy będziesz chciał wypowiedzieć się na Wielopokoleniowych. Nie będę tolerował słów powszechnie uważanych za obelżywe albo nazbyt personalnych komentarzy. Wiem, że żyjemy w wolnym kraju, ale każda wolność ma swoje granice. Dokładnie tam, gdzie zaczyna się wonność i godność osobista innych osób. Lub, z innej strony, zwyczajne chamstwo. Nazywajmy rzeczy po imieniu. Dlatego - szanując własną godność osobistą oraz spokój sumienia - uprzedzam, że zastrzegam sobie prawo do interwencji. Mam nadzieję, że jako moderator nie będę musiał zbyt często się aktywizować, ale to mój blog i moje zasady. Wolność polega także na tym, że jeśli Ci one nie odpowiadają, po prostu pozwól sobie tutaj nie zaglądać. Przepraszam, że tak stawiam sprawę, ale uważam, że coraz częściej zbyt wielu nazbyt dużo sobie pozwala. Puszczają hamulce i słoma z butów wyłazi… Ale to jeszcze inny temat. O savoir-vivre na Wieolopokoleniowych także będzie. A co!? Mój blog, wolno mi! ;) Oczywiście krytyka, najlepiej konstruktywna i merytoryczna, zawsze będzie mile widziana. Ale krytyka powinna być ad rem, a nie ad personam. Ma dotyczyć spraw, racji, poglądów, a nawet tzw. prawd podstawowych, jakkolwiek je rozumiemy. Ale nie ludzi i ich godności osobistej. Bo każdy ją ma. Tak samo chcę zastrzec, że pragnę pozostać apolityczny. Tak, zdarzy się zapewne, że będzie tutaj o poglądach, postawach społecznych, rozwiązaniach prawnych promowanych przez (akurat) tę czy inną partię, czy podstawowych wartościach, jak patriotyzm, wolność, religia itp. itd. Ale niekoniecznie o konkretnych partiach i aktualnie rządzących lub opozycyjnych politykach. Niezależnie od opcji i kadencji. A już na pewno nie dam się wkręcić, że krytyka określonych rozwiązań czy poglądów jest jednoznaczna (i jedynie w ten sposób ma być rozumiana), jako krytyka określonej partii, religii czy nacji (itp. itd.). Co ostatnio bywa modne. Nie lubię generalizowania i upraszczania do absurdu. To tyle o polityce. Mam nadzieję, że więcej nie będzie.',
  },
];

export default rules;
